modLoader = "javafml"
loaderVersion = "[4,)"
issueTrackerURL = "https://github.com/mahmudindev/mcmod-largebiomesdimension"
license = "ARR"

[[mods]]
modId = "largebiomesdimension"
version = "${version}"
displayName = "Large Biomes Dimension"
authors = "mahmudindev"
description = '''
Add large biomes as separate dimension.
'''
logoFile = "assets/largebiomesdimension/icon.png"

[[dependencies.largebiomesdimension]]
modId = "neoforge"
type = "required"
versionRange = "[21.0,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.largebiomesdimension]]
modId = "minecraft"
type = "required"
versionRange = "[1.21,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.largebiomesdimension]]
modId = "worldportal"
type = "required"
versionRange = "[0.0.9,)"
ordering = "NONE"
side = "SERVER"

[[mixins]]
config = "largebiomesdimension.mixins.json"
